### PR TITLE
Theme-switcher

### PR DESCRIPTION
**Pull request by PranavBakre**
Signed-off-by: Pranav Bakre <pranavbakre@yahoo.in>

### CODE REVIEW

**Comment by rittmang** [comment]
Blame yourself.

**Comment by akhilnarang** [comment]
I vote don't merge because of that commit message.

**Comment by PranavBakre** [comment]
> I vote don't merge because of that commit message.

was supposed to be amended but @ksdfg and @vigu184 failed to fix it

**Review by prkprime — COMMENTED** [review]
Pero af but me no js 🤷

**Review by vigu184 — CHANGES_REQUESTED** [review]
On expanding the Toolbar, "Change Theme" is still black in text and is almost invisible.

**Pull request merged**
